In [1]:
# Convert list of numeric value into 1-D Numpy Array
import numpy as np
l= [12.23, 13.32, 100, 36.32] 
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


In [2]:
# Create a 3x3 matrix with values ranging from 2 to 10. 
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
# Create a null vector of size 10 and update sixth value to 11
x=np.zeros(10)
x[6] = 11
print(x)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [4]:
# Reverse an array
x = np.arange(12,38)
x= x[::-1]
print (x)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [5]:
# create a 2d array with 1 on the border and 0 inside
x = np.ones((5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
# Add a border (filled with 0's) around an existing array. 
x = np.ones((3,3))
x = np.pad(x,pad_width=1, mode='constant', constant_values=0)
print(x)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
#  create a 8x8 matrix and fill it with a checkerboard pattern.
x = np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
# convert a list and tuple into arrays
l = [1,2,3,4,5,6,7,8]
a1 = np.asarray(l)
print(a1)
t = ([8, 4, 6], [1, 2, 3])
a2 = np.asarray(t)
print(a2)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [9]:
#  append values to the end of an array.
arr = [10, 20, 30] 
arr = np.append(arr, [40,50,60,70,80,90])
print(arr)

[10 20 30 40 50 60 70 80 90]


In [10]:
#  to find the real and imaginary parts of an array of complex numbers. 
num = [1.00000000 + 0.j, 0.70710678 + 0.70710678j]
com_arr = np.array(num)
print(com_arr)
for i in range(len(com_arr)): 
    print("Real value:", com_arr[i].real)
    print("Imaginary value:", com_arr[i].imag)

[1.        +0.j         0.70710678+0.70710678j]
Real value: 1.0
Imaginary value: 0.0
Real value: 0.70710678
Imaginary value: 0.70710678


In [11]:
# to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements
array = np.array([1.0,3.3,5.2])
print("Size of array", array.size)
print("Length of one array element in bytes", array.itemsize)
print("Total bytes consumed by elements of array", array.nbytes)

Size of array 3
Length of one array element in bytes 8
Total bytes consumed by elements of array 24


In [12]:
# find common values between two arrays.
x = np.array([0, 10, 20, 40, 60])
y = np.array([10, 30, 40])
print(np.intersect1d(x,y))

[10 40]


In [13]:
#  find the set difference of two arrays
x =  np.array([0, 10, 20, 40, 60, 80])
y =  np.array([10, 30, 40, 50, 70, 90])
print("Set Difference between two arrays", np.setdiff1d(x,y))

Set Difference between two arrays [ 0 20 60 80]


In [14]:
# find the set exclusive-or of two arrays
x =  np.array([0, 10, 20, 40, 60, 80])
y =  np.array([10, 30, 40, 50, 70])
print("Set exclusive between two arrays", np.setxor1d(x,y))

Set exclusive between two arrays [ 0 20 30 50 60 70 80]


In [15]:
# compare two arrays 
a = np.array([1,2])
b = np.array([4,5])
result1 = a > b
result2 = a >= b
result3 = a < b
print(result1.all(), result2.all(), result3.all())

False False True


In [16]:
# save a NumPy array to a text file
  
x = np.arange(0, 10, 1)
c = np.savetxt('file.txt', x, delimiter =', ', fmt = '%s')   



In [17]:
# create a contiguous flattened array
arr = np.array([[5,6,7],[8,9,10]])
flattened_array = np.ravel(arr)
print("New flattened array ", flattened_array)

New flattened array  [ 5  6  7  8  9 10]


In [18]:
# change the data type of an array.
arr = np.array([10,20,30,40,50])
print( arr, "\n", arr.dtype)
arr = arr.astype('float')
print(arr ,"\n", arr.dtype)

[10 20 30 40 50] 
 int32
[10. 20. 30. 40. 50.] 
 float64


In [19]:
# ones on a diagonal and zeros elsewhere. 
a = np.eye(3, dtype = float)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
# create array as below
x = np.zeros((4,3))
for i in range(1, len(x)):
    x[i:i+1, 0:i] = 1
print(x)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [21]:
# concatenate two 2-dimensional arrays.
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print(np.concatenate((arr1,arr2), axis = 1))

[[1 2 5 6]
 [3 4 7 8]]


In [22]:
# program to make an array immutable (read-only). 
a = np.zeros(11)
print(a)
a[1] = 2
print(a)
a.flags.writeable = False
a[1] = 7
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

In [23]:
# create an array of (3, 4) shape, multiply every element value by 3 and display the new array. 
a = np.arange(0,12).reshape(3,4)
print("Original array\n ", a)
a*=3
print("New array eleents\n ", a)

Original array
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array eleents
  [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [24]:
# convert a NumPy array into Python list structure. 
arr = np.array([[0 ,1] ,[2 ,3] ,[4,5]] )
print("Array\n ", arr)
print(type(arr))
lis = arr.tolist()
print("List ", lis)
print(type(lis))

Array
  [[0 1]
 [2 3]
 [4 5]]
<class 'numpy.ndarray'>
List  [[0, 1], [2, 3], [4, 5]]
<class 'list'>


In [25]:
#  convert a NumPy array into Python list structure. 
arr = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,0.35399976, 0.99469633, 0.0694458, 0.54711478] )
print("Array\n ", arr)
lis = arr.tolist()
roundoff = np.round_(lis, decimals = 3)
print("List ", roundoff)

Array
  [0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
List  [0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


In [26]:
# program to suppresses the use of scientific notation for small numbers in numpy array.
num = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
np.set_printoptions(precision = 3, suppress = True)
print("Array values with precision 3", num)

Array values with precision 3 [   0.       1.6   1200.       0.235]


In [27]:
#  add an extra column to an numpy array.
arr = np.array([[10,20,30], [40,50,60]])
print(arr)
arr = np.append(arr, np.array([[100], [200]]), axis = 1)
print(arr)

[[10 20 30]
 [40 50 60]]
[[ 10  20  30 100]
 [ 40  50  60 200]]


In [28]:
#  remove specific elements in a numpy array. 
a = np.array([ 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array", a)
a=np.delete(a,[0,3,4])
print("Array after deletion is ",  a)

Original array [ 10  20  30  40  50  60  70  80  90 100]
Array after deletion is  [ 20  30  60  70  80  90 100]
